In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("qoute_dataset.csv")

In [ ]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [ ]:
df.shape

(3038, 2)

In [ ]:
quotes = df['quote']
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [ ]:
# converting string into lowercase
quotes = quotes.str.lower()

In [ ]:
# removing punctuation:
import string
translator = str.maketrans('', '', string.punctuation)
quotes = quotes.apply(lambda x: x.translate(translator))

In [ ]:
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
2    “there are only two ways to live your life one...
3    “the person be it gentleman or lady who has no...
4    “imperfection is beauty madness is genius and ...
Name: quote, dtype: object

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
# tokenization:

# vocab_size = 10000
vocab_size = 8978 # changed the vocab_size because the model training was taking too long to complete

tokinizer = Tokenizer(num_words=vocab_size)
tokinizer.fit_on_texts(quotes)

In [ ]:
word_index = tokinizer.word_index
print(len(word_index))
list(word_index.items())[:10]

8978

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [ ]:
# words are converted to numbers, now we will create a sequence
sequence = tokinizer.texts_to_sequences(quotes)

In [ ]:
# original quotes:
for i in range(3):
  print(quotes[i])

“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”
“it is our choices harry that show what we truly are far more than our abilities”
“there are only two ways to live your life one is as though nothing is a miracle the other is as though everything is a miracle”

In [ ]:
# sequenced quotes:
for i in range(3):
  print(sequence[i])

[713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104, 752, 70, 2461]
[947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70, 3676]
[1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1, 101, 7, 29, 329, 126, 7, 5, 3677]

In [ ]:
X = []
y = []

for seq in sequence:
  for i in range(1,len(seq)):
    input_seq = seq[:i]
    output_seq = seq[i]
    X.append(input_seq)
    y.append(output_seq)

In [ ]:
len(X)

85270

In [ ]:
len(y)

85270

# **X me jo input size hai wo different hai. To usko same karne ke liye hum padding ka use karenge**

In [ ]:
# max_len isliye nikala taaki input ka ek length fix kar sake and then padding apply kare uss input pe jo chota hai
max_len = max(len(x) for x in X)
print(max_len)

745

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_padded = pad_sequences(X, maxlen=max_len, padding='pre')

In [ ]:
X_padded

array([[   0,    0,    0, ...,    0,    0,  713],
       [   0,    0,    0, ...,    0,  713,   62],
       [   0,    0,    0, ...,  713,   62,   29],
       ...,
       [   0,    0,    0, ...,    9,   19, 1125],
       [   0,    0,    0, ...,   19, 1125,    3],
       [   0,    0,    0, ..., 1125,    3,  169]], dtype=int32)

In [ ]:
X_padded[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0, 713], dtype=int32)

In [ ]:
X[0]

[713]

In [ ]:
y = np.array(y)

In [ ]:
X_padded.shape

(85270, 745)

In [ ]:
y.shape

(85270,)

In [ ]:
from tensorflow.keras.utils import to_categorical
y_one_hot = to_categorical(y, num_classes=vocab_size)

In [ ]:
y_one_hot.shape

(85270, 8978)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN,LSTM, Dense

In [ ]:
embedding_dim = 50
rnn_units = 128

In [ ]:
rnn_model = Sequential()

rnn_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len)
)
rnn_model.add(SimpleRNN(units=rnn_units))
rnn_model.add(Dense(units=vocab_size, activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [ ]:
rnn_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [ ]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
lstm_model = Sequential()
lstm_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len)
)
lstm_model.add(LSTM(units=rnn_units))
lstm_model.add(Dense(units=vocab_size, activation='softmax'))

In [ ]:
lstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [ ]:
lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
epochs = 100
batch_size = 128

In [ ]:
history_rnn = lstm_model.fit(
    X_padded, y_one_hot,
    epochs=epochs,
    batch_size=batch_size,
    validation_split=0.1
)

Epoch 1/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 37s 53ms/step - accuracy: 0.0358 - loss: 7.0559 - val_accuracy: 0.0452 - val_loss: 6.6754
Epoch 2/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 38s 53ms/step - accuracy: 0.0528 - loss: 6.3510 - val_accuracy: 0.0699 - val_loss: 6.5277
Epoch 3/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.0788 - loss: 6.0482 - val_accuracy: 0.0876 - val_loss: 6.4663
Epoch 4/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.0934 - loss: 5.8551 - val_accuracy: 0.0937 - val_loss: 6.4264
Epoch 5/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1062 - loss: 5.6685 - val_accuracy: 0.0994 - val_loss: 6.4168
Epoch 6/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.1197 - loss: 5.4795 - val_accuracy: 0.1039 - val_loss: 6.4162
Epoch 7/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.1269 - loss: 5.3165 - val_accuracy: 0.1061 - val_loss: 6.4442
Epoch 8/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.1351 - loss: 5.1637 - val_accuracy: 0.1080 - val_loss: 6.4770
Epoch 9/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.1421 - loss: 5.0307 - val_accuracy: 0.1074 - val_loss: 6.5207
Epoch 10/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.1498 - loss: 4.8986 - val_accuracy: 0.1085 - val_loss: 6.5633
Epoch 11/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1548 - loss: 4.7579 - val_accuracy: 0.1104 - val_loss: 6.6245
Epoch 12/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.1647 - loss: 4.6394 - val_accuracy: 0.1091 - val_loss: 6.6769
Epoch 13/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.1732 - loss: 4.5064 - val_accuracy: 0.1121 - val_loss: 6.7210
Epoch 14/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.1830 - loss: 4.3976 - val_accuracy: 0.1120 - val_loss: 6.8131
Epoch 15/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1958 - loss: 4.2642 - val_accuracy: 0.1106 - val_loss: 6.8724
Epoch 16/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2082 - loss: 4.1528 - val_accuracy: 0.1134 - val_loss: 6.9706
Epoch 17/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2186 - loss: 4.0498 - val_accuracy: 0.1119 - val_loss: 7.0245
Epoch 18/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2355 - loss: 3.9348 - val_accuracy: 0.1131 - val_loss: 7.1153
Epoch 19/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2506 - loss: 3.8391 - val_accuracy: 0.1109 - val_loss: 7.1868
Epoch 20/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2626 - loss: 3.7505 - val_accuracy: 0.1119 - val_loss: 7.2720
Epoch 21/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.2771 - loss: 3.6614 - val_accuracy: 0.1107 - val_loss: 7.3610
Epoch 22/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 53ms/step - accuracy: 0.2906 - loss: 3.5687 - val_accuracy: 0.1101 - val_loss: 7.4191
Epoch 23/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.3036 - loss: 3.4908 - val_accuracy: 0.1079 - val_loss: 7.5188
Epoch 24/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3150 - loss: 3.4184 - val_accuracy: 0.1074 - val_loss: 7.5881
Epoch 25/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.3240 - loss: 3.3599 - val_accuracy: 0.1047 - val_loss: 7.6654
Epoch 26/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.3316 - loss: 3.2980 - val_accuracy: 0.1058 - val_loss: 7.7442
Epoch 27/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.3387 - loss: 3.2380 - val_accuracy: 0.1037 - val_loss: 7.8080
Epoch 28/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3529 - loss: 3.1708 - val_accuracy: 0.1026 - val_loss: 7.8736
Epoch 29/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.3647 - loss: 3.1052 - val_accuracy: 0.1030 - val_loss: 7.9497
Epoch 30/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3729 - loss: 3.0540 - val_accuracy: 0.1054 - val_loss: 8.0266
Epoch 31/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.3856 - loss: 2.9950 - val_accuracy: 0.1032 - val_loss: 8.1103
Epoch 32/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3950 - loss: 2.9365 - val_accuracy: 0.1019 - val_loss: 8.1499
Epoch 33/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.3990 - loss: 2.8977 - val_accuracy: 0.0991 - val_loss: 8.2225
Epoch 34/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.4121 - loss: 2.8375 - val_accuracy: 0.0998 - val_loss: 8.2818
Epoch 35/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4204 - loss: 2.7905 - val_accuracy: 0.0987 - val_loss: 8.3501
Epoch 36/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.4250 - loss: 2.7548 - val_accuracy: 0.0965 - val_loss: 8.4145
Epoch 37/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.4336 - loss: 2.7146 - val_accuracy: 0.0945 - val_loss: 8.4838
Epoch 38/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.4426 - loss: 2.6593 - val_accuracy: 0.0945 - val_loss: 8.5471
Epoch 39/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.4474 - loss: 2.6266 - val_accuracy: 0.0986 - val_loss: 8.6019
Epoch 40/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.4577 - loss: 2.5757 - val_accuracy: 0.0955 - val_loss: 8.6543
Epoch 41/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4661 - loss: 2.5381 - val_accuracy: 0.0951 - val_loss: 8.7341
Epoch 42/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4680 - loss: 2.5087 - val_accuracy: 0.0932 - val_loss: 8.7736
Epoch 43/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.4761 - loss: 2.4760 - val_accuracy: 0.0956 - val_loss: 8.8487
Epoch 44/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.4869 - loss: 2.4300 - val_accuracy: 0.0922 - val_loss: 8.8872
Epoch 45/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.4912 - loss: 2.3878 - val_accuracy: 0.0934 - val_loss: 8.9570
Epoch 46/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5006 - loss: 2.3454 - val_accuracy: 0.0901 - val_loss: 9.0119
Epoch 47/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5039 - loss: 2.3242 - val_accuracy: 0.0909 - val_loss: 9.0765
Epoch 48/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5098 - loss: 2.2834 - val_accuracy: 0.0912 - val_loss: 9.1300
Epoch 49/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5163 - loss: 2.2549 - val_accuracy: 0.0925 - val_loss: 9.1752
Epoch 50/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5231 - loss: 2.2156 - val_accuracy: 0.0924 - val_loss: 9.2167
Epoch 51/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.5308 - loss: 2.1823 - val_accuracy: 0.0905 - val_loss: 9.3075
Epoch 52/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5343 - loss: 2.1588 - val_accuracy: 0.0904 - val_loss: 9.3401
Epoch 53/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5388 - loss: 2.1337 - val_accuracy: 0.0881 - val_loss: 9.3972
Epoch 54/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5443 - loss: 2.1035 - val_accuracy: 0.0887 - val_loss: 9.4650
Epoch 55/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5503 - loss: 2.0800 - val_accuracy: 0.0891 - val_loss: 9.5215
Epoch 56/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.5562 - loss: 2.0448 - val_accuracy: 0.0890 - val_loss: 9.5656
Epoch 57/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5644 - loss: 2.0137 - val_accuracy: 0.0915 - val_loss: 9.6275
Epoch 58/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 52ms/step - accuracy: 0.5647 - loss: 2.0101 - val_accuracy: 0.0912 - val_loss: 9.6811
Epoch 59/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5739 - loss: 1.9642 - val_accuracy: 0.0875 - val_loss: 9.7080
Epoch 60/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5790 - loss: 1.9413 - val_accuracy: 0.0889 - val_loss: 9.7664
Epoch 61/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5834 - loss: 1.9109 - val_accuracy: 0.0861 - val_loss: 9.8458
Epoch 62/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5882 - loss: 1.8960 - val_accuracy: 0.0882 - val_loss: 9.9132
Epoch 63/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5911 - loss: 1.8797 - val_accuracy: 0.0855 - val_loss: 9.9339
Epoch 64/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5994 - loss: 1.8421 - val_accuracy: 0.0871 - val_loss: 10.0004
Epoch 65/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6000 - loss: 1.8362 - val_accuracy: 0.0865 - val_loss: 10.0459
Epoch 66/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6059 - loss: 1.8054 - val_accuracy: 0.0857 - val_loss: 10.0944
Epoch 67/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6110 - loss: 1.7812 - val_accuracy: 0.0848 - val_loss: 10.1563
Epoch 68/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6083 - loss: 1.8244 - val_accuracy: 0.0848 - val_loss: 10.1874
Epoch 69/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6198 - loss: 1.7468 - val_accuracy: 0.0854 - val_loss: 10.2190
Epoch 70/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6236 - loss: 1.7227 - val_accuracy: 0.0858 - val_loss: 10.3140
Epoch 71/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6247 - loss: 1.7124 - val_accuracy: 0.0849 - val_loss: 10.3458
Epoch 72/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6297 - loss: 1.6899 - val_accuracy: 0.0844 - val_loss: 10.3697
Epoch 73/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6348 - loss: 1.6635 - val_accuracy: 0.0853 - val_loss: 10.4389
Epoch 74/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6403 - loss: 1.6430 - val_accuracy: 0.0834 - val_loss: 10.4887
Epoch 75/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 53ms/step - accuracy: 0.6433 - loss: 1.6273 - val_accuracy: 0.0827 - val_loss: 10.5261
Epoch 76/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6455 - loss: 1.6178 - val_accuracy: 0.0815 - val_loss: 10.5890
Epoch 77/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6501 - loss: 1.5931 - val_accuracy: 0.0810 - val_loss: 10.6140
Epoch 78/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6575 - loss: 1.5669 - val_accuracy: 0.0819 - val_loss: 10.6927
Epoch 79/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6576 - loss: 1.5510 - val_accuracy: 0.0835 - val_loss: 10.7318
Epoch 80/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6621 - loss: 1.5438 - val_accuracy: 0.0810 - val_loss: 10.7412
Epoch 81/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6658 - loss: 1.5189 - val_accuracy: 0.0831 - val_loss: 10.8121
Epoch 82/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6673 - loss: 1.5102 - val_accuracy: 0.0813 - val_loss: 10.8625
Epoch 83/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6713 - loss: 1.4959 - val_accuracy: 0.0813 - val_loss: 10.9413
Epoch 84/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6766 - loss: 1.4669 - val_accuracy: 0.0800 - val_loss: 10.9721
Epoch 85/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 53ms/step - accuracy: 0.6766 - loss: 1.4632 - val_accuracy: 0.0795 - val_loss: 11.0141
Epoch 86/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6831 - loss: 1.4427 - val_accuracy: 0.0809 - val_loss: 11.0671
Epoch 87/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6858 - loss: 1.4228 - val_accuracy: 0.0781 - val_loss: 11.1015
Epoch 88/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6904 - loss: 1.4100 - val_accuracy: 0.0809 - val_loss: 11.1299
Epoch 89/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6899 - loss: 1.4075 - val_accuracy: 0.0793 - val_loss: 11.1892
Epoch 90/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6960 - loss: 1.3815 - val_accuracy: 0.0781 - val_loss: 11.2409
Epoch 91/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6957 - loss: 1.3767 - val_accuracy: 0.0786 - val_loss: 11.2814
Epoch 92/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6995 - loss: 1.3591 - val_accuracy: 0.0785 - val_loss: 11.3333
Epoch 93/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7014 - loss: 1.3463 - val_accuracy: 0.0773 - val_loss: 11.3649
Epoch 94/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.7066 - loss: 1.3308 - val_accuracy: 0.0789 - val_loss: 11.4262
Epoch 95/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7122 - loss: 1.3115 - val_accuracy: 0.0787 - val_loss: 11.4511
Epoch 96/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.7117 - loss: 1.2991 - val_accuracy: 0.0781 - val_loss: 11.5101
Epoch 97/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.7129 - loss: 1.2910 - val_accuracy: 0.0792 - val_loss: 11.5352
Epoch 98/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7184 - loss: 1.2851 - val_accuracy: 0.0780 - val_loss: 11.6025
Epoch 99/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7171 - loss: 1.2763 - val_accuracy: 0.0778 - val_loss: 11.6495
Epoch 100/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.7231 - loss: 1.2504 - val_accuracy: 0.0769 - val_loss: 11.6860

In [ ]:
lstm_model.save("lstm_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [ ]:
index_to_word = {}
for word, index in word_index.items():
  index_to_word[index] = word

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
def predictor(model,tokenizer,text,max_len):
  text = text.lower()

  seq = tokenizer.texts_to_sequences([text])[0]
  seq = pad_sequences([seq], maxlen=max_len, padding='pre')

  pred = model.predict(seq,verbose = 0)
  pred_index = np.argmax(pred)
  return index_to_word[pred_index]

In [ ]:
seed_text = "what are you"
next_word = predictor(lstm_model,tokinizer,seed_text,max_len)
print(next_word)

worrying

In [ ]:
def generate_text(model,tokenizer,seed_text,max_len,n_words):
  for _ in range(n_words):
    next_word = predictor(model,tokenizer,seed_text,max_len)
    if next_word == "":
      break
    seed_text += " " + next_word
  return seed_text

In [ ]:
seed = "are you a"
generate_text = generate_text(lstm_model,tokinizer,seed,max_len,10)
print(generate_text)

are you a christian must also think that is in love for a

In [ ]:
import pickle
with open("tokenizer.pkl", "wb") as f:
  pickle.dump(tokinizer, f)

In [ ]:
with open("max_len.pkl", "wb") as f:
  pickle.dump(max_len, f)